#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

install_plugin() {
  local PLUGIN_NAME="${1}"

  rm -rf "${TEXT_PKG:?}/${PLUGIN_NAME}"
  ln -s "${SCRIPT_DIR}/plugins/${PLUGIN_NAME}" "${TEXT_PKG}/${PLUGIN_NAME}"
}

symlink_settings() {
  local USER_SETTINGS="${1}/User"

  rm -rf "${USER_SETTINGS:?}"/*
  mkdir -p "${USER_SETTINGS}"

  if [[ -d "${SCRIPT_DIR}/${2}/settings/" ]]; then
    ln -s "${SCRIPT_DIR}/${2}/settings/"* "${USER_SETTINGS}/"
  fi

  if [[ -d "${SCRIPT_DIR}/${2}/snippets/" ]]; then
    ln -s "${SCRIPT_DIR}/${2}/snippets/"* "${USER_SETTINGS}/"
  fi
}

install_terraform_lsp() {
  local TERRAFORM_LSP_VERSION="0.0.10"
  local TERRAFORM_LSP_OS="linux"
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    TERRAFORM_LSP_OS="darwin"
  fi

  local EXTRACT_FILENAME="terraform-lsp_${TERRAFORM_LSP_VERSION}_${TERRAFORM_LSP_OS}_amd64"
  local EXTRACT_URL="https://github.com/juliosueiras/terraform-lsp/releases/download/v${TERRAFORM_LSP_VERSION}/${EXTRACT_FILENAME}.tar.gz"
  local EXTRACT_FOLDER="/tmp"
  local EXTRACT_PATH="${EXTRACT_FOLDER}/${EXTRACT_FILENAME}.tar.gz"

  curl -q -sSL --max-time 300 -o "${EXTRACT_PATH}" "${EXTRACT_URL}"
  (
    cd "${EXTRACT_FOLDER}"
    mkdir -p "${EXTRACT_FILENAME}"
    tar xzf "${EXTRACT_PATH}" -C "${EXTRACT_FILENAME}"
    mv "${EXTRACT_FILENAME}/terraform-lsp" "${HOME}/opt/bin/"
    rm -rf "${EXTRACT_PATH}" "${EXTRACT_FILENAME}"
  )
}

main() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    local TEXT_PKG="${HOME}/Library/Application Support/Sublime Text/Packages"
    local MERGE_PKG="${HOME}/Library/Application Support/Sublime Merge/Packages"
  fi

  symlink_settings "${TEXT_PKG}" "text"
  symlink_settings "${MERGE_PKG}" "merge"

  install_plugin SublimeGit
  install_plugin SublimeGo
  install_plugin SublimeLayout
  install_plugin SublimeTerraform

  if command -v go > /dev/null 2>&1; then
    GO111MODULE=on go get golang.org/x/tools/gopls@latest
    go get -u golang.org/x/tools/cmd/gotype
  fi

  if command -v npm > /dev/null 2>&1; then
    npm install -g prettier javascript-typescript-langserver
  fi

  if command -v python > /dev/null 2>&1; then
    pip install --user python-language-server pycodestyle
  fi

  if command -v terraform > /dev/null 2>&1; then
    install_terraform_lsp
  fi
}

main "${@:-}"
