#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

install_plugin() {
  local PLUGIN_NAME="${1}"

  rm -rf "${TEXT_PKG:?}/${PLUGIN_NAME}"
  ln -s "${SCRIPT_DIR}/plugins/${PLUGIN_NAME}" "${TEXT_PKG}/${PLUGIN_NAME}"
}

symlink_settings() {
  local USER_SETTINGS="${1}/User"

  rm -rf "${USER_SETTINGS:?}"/*
  mkdir -p "${USER_SETTINGS}"

  if [[ -d "${SCRIPT_DIR}/${2}/settings/" ]]; then
    ln -s "${SCRIPT_DIR}/${2}/settings/"* "${USER_SETTINGS}/"
  fi

  if [[ -d "${SCRIPT_DIR}/${2}/snippets/" ]]; then
    ln -s "${SCRIPT_DIR}/${2}/snippets/"* "${USER_SETTINGS}/"
  fi
}

install_terraform_lsp() {
  local TERRAFORM_LSP_VERSION="0.0.10"
  local TERRAFORM_LSP_OS="linux"
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    TERRAFORM_LSP_OS="darwin"
  fi

  archive_to_binary "https://github.com/juliosueiras/terraform-lsp/releases/download/v${TERRAFORM_LSP_VERSION}/terraform-lsp_${TERRAFORM_LSP_VERSION}_${TERRAFORM_LSP_OS}_amd64.tar.gz" "terraform-lsp"
}

main() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    local TEXT_PKG="${HOME}/Library/Application Support/Sublime Text/Packages"
    local MERGE_PKG="${HOME}/Library/Application Support/Sublime Merge/Packages"
  fi

  source "${SCRIPT_DIR}/../sources/_binary"

  symlink_settings "${TEXT_PKG}" "text"
  symlink_settings "${MERGE_PKG}" "merge"

  install_plugin SublimeGit
  install_plugin SublimeGo
  install_plugin SublimeLayout
  install_plugin SublimeTerraform

  if command -v go > /dev/null 2>&1; then
    GO111MODULE=on go get golang.org/x/tools/gopls@latest
    go get -u golang.org/x/tools/cmd/gotype
  fi

  if command -v npm > /dev/null 2>&1; then
    npm install -g prettier javascript-typescript-langserver
  fi

  if command -v pip > /dev/null 2>&1; then
    pip install --user python-language-server pycodestyle
  fi

  install_terraform_lsp
}

main "${@:-}"
