#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/scripts/meta" && meta_init "github"

  rg "CTOP_VERSION=" install/
  github_last_release bcicen/ctop

  rg "SYNCTHING_VERSION=" install/
  github_last_release syncthing/syncthing

  rg "TERRAFORM_VERSION=" install/
  github_last_release hashicorp/terraform

  rg "PGCLI_VERSION=" install/
  github_last_release dbcli/pgcli
}

main
