#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/scripts/meta" && meta_init "github"

  github_last_release bcicen/ctop "v$(rg 'CTOP_VERSION="(\S+)"' -r '$1' -N --no-filename -o install/)"
  github_last_release syncthing/syncthing "v$(rg 'SYNCTHING_VERSION="(\S+)"' -r '$1' -N --no-filename -o install/)"
  github_last_release hashicorp/terraform "v$(rg 'TERRAFORM_VERSION="(\S+)"' -r '$1' -N --no-filename -o install/)"
}

main
