#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

main() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  source "${SCRIPT_DIR}/scripts/meta" && meta_init "github" "version"

  github_last_release bcicen/ctop "v$(version_value 'CTOP_VERSION="(.*)"' install/)"
  github_last_release syncthing/syncthing "v$(version_value 'SYNCTHING_VERSION="(.*)"' install/)"
  github_last_release hashicorp/terraform "v$(version_value 'TERRAFORM_VERSION="(.*)"' install/)"
  github_last_release dandavison/delta "$(version_value 'DELTA_VERSION="(.*)"' install/)"
  github_last_release travis-ci/travis.rb "$(version_value 'TRAVIS_VERSION="(.*)"' install/)"
}

main
