#!/usr/bin/env bash

git clone git@github.com:ViBiOh/fibr.git
git clone git@github.com:ViBiOh/funds.git
git clone git@github.com:ViBiOh/go-api.git
git clone git@github.com:ViBiOh/auth.git
git clone git@github.com:ViBiOh/dashboard.git
git clone git@github.com:ViBiOh/alcotest.git
git clone git@github.com:ViBiOh/viws.git
git clone git@github.com:ViBiOh/eponae-api.git
git clone git@github.com:ViBiOh/iot.git
git clone git@github.com:ViBiOh/httputils.git
git clone git@github.com:ViBiOh/docker-elk.git
git clone git@github.com:ViBiOh/traefik-config.git
git clone git@github.com:ViBiOh/docker-monitoring.git
git clone git@github.com:ViBiOh/raspberry-config.git
git clone git@github.com:ViBiOh/about-me.git
git clone git@github.com:ViBiOh/spring-web-bp.git
git clone git@github.com:ViBiOh/funtch.git
git clone git@github.com:ViBiOh/react-bp.git
git clone git@github.com:ViBiOh/site-montdenis.git
git clone git@github.com:ViBiOh/site-domaine.git
git clone git@github.com:ViBiOh/genie-logiciel.git
git clone git@github.com:ViBiOh/talks.git
git clone git@github.com:ViBiOh/js-index-builder.git
git clone git@github.com:ViBiOh/spring-tictactoe.git
git clone git@github.com:ViBiOh/docker-sonar.git
git clone git@github.com:ViBiOh/docker-travis-cli.git
git clone git@github.com:ViBiOh/mars-rover.git
git clone git@github.com:ViBiOh/docker-wordpress.git
git clone git@github.com:ViBiOh/docker-nginx.git
git clone git@github.com:ViBiOh/docker-mariadb.git
git clone git@github.com:ViBiOh/docker-ftp.git
git clone git@github.com:ViBiOh/docker-selenium.git
git clone git@github.com:ViBiOh/js-break-sync.git
git clone git@github.com:ViBiOh/node-logger.git
git clone git@github.com:ViBiOh/node-bp.git
git clone git@github.com:ViBiOh/js-utils.git
git clone git@github.com:ViBiOh/js-dichotomic.git
git clone git@github.com:ViBiOh/docker-tools.git
git clone git@github.com:ViBiOh/docker-php.git
git clone git@github.com:ViBiOh/postman-to-gatling.git
git clone git@github.com:ViBiOh/docker-phpmyadmin.git
git clone git@gitlab.com:ViBiOh/coreos-cloudinit.git
