#!/usr/bin/env bash

archive_to_binary() {
  if [[ ${#} -lt 2 ]]; then
    var_error "Usage: archive_to_binary [URL] [BINARY_PATH] [BINARY_DESTINATION=${HOME}/opt/bin/]"
    return 1
  fi

  local ARCHIVE_URL="${1}"
  local BINARY_PATH="${2}"
  local BINARY_DESTINATION="${3:-${HOME}/opt/bin/}"

  local ARCHIVE_FILENAME
  local ARCHIVE_EXTENSION
  if [[ ${ARCHIVE_URL} =~ .*\/(.*)\.(tar\.gz|zip) ]]; then
    ARCHIVE_FILENAME="${BASH_REMATCH[1]}"
    ARCHIVE_EXTENSION="${BASH_REMATCH[2]}"
  else
    var_error "download_tar: unable to extract archive filename and extension from ${URL}"
    return 1
  fi

  local TEMP_FOLDER="/tmp"
  local ARCHIVE_PATH="${TEMP_FOLDER}/${ARCHIVE_FILENAME}.${ARCHIVE_EXTENSION}"

  curl -q -sSL --max-time 300 -o "${ARCHIVE_PATH}" "${ARCHIVE_URL}"
  (
    cd "${TEMP_FOLDER}" || false
    mkdir -p "${ARCHIVE_FILENAME}"

    if [[ ${ARCHIVE_EXTENSION} == "tar.gz" ]]; then
      tar xzf "${ARCHIVE_PATH}" -C "${ARCHIVE_FILENAME}"
    elif [[ ${ARCHIVE_EXTENSION} == "zip" ]]; then
      unzip "${ARCHIVE_PATH}" -d "${ARCHIVE_FILENAME}"
    fi

    mv "${ARCHIVE_FILENAME}/${BINARY_PATH}" "${BINARY_DESTINATION}"
    rm -rf "${ARCHIVE_PATH}" "${ARCHIVE_FILENAME}"
  )
}
