#!/usr/bin/env bash

if [[ -d "${HOME}/opt/bin" ]]; then
  export PATH="${HOME}/opt/bin:${PATH}"
fi

export DEFAULT_OPENER="xdg-open"
if command -v open > /dev/null 2>&1; then
  DEFAULT_OPENER="open"
fi
