#!/usr/bin/env bash

if [[ -d "${HOME}/opt/go/bin" ]]; then
  export PATH="${HOME}/opt/go/bin:${PATH}"
fi

if ! command -v go >/dev/null 2>&1; then
  return
fi

export GOPATH="${HOME}/opt/gopath"
export PATH="${GOPATH}/bin:${PATH}"

alias pprof_cpu='go tool pprof -http localhost:8080 http://localhost:9999/debug/pprof/profile'
alias pprof_memory='go tool pprof -http localhost:8080 http://localhost:9999/debug/pprof/heap'
alias pprof_goroutine='go tool pprof -http localhost:8080 http://localhost:9999/debug/pprof/goroutine'

if command -v fzf >/dev/null 2>&1; then
  go_bump() {
    local MODULE_TO_BUMP
    MODULE_TO_BUMP="$(go list -m -json all | jq -r 'select(.Indirect != true) | .Path' | fzf --height=20 --ansi --reverse -1 --query="${1:-}")"

    if [[ -n ${MODULE_TO_BUMP} ]]; then
      local MODULE_VERSION=""

      var_read MODULE_VERSION "latest"
      if [[ -n ${MODULE_VERSION} ]]; then
        MODULE_VERSION="@${MODULE_VERSION}"
      fi

      var_print_and_run "go get -d '${MODULE_TO_BUMP}${MODULE_VERSION}'"
    fi
  }
fi

credentials() {
  if ! command -v pass >/dev/null 2>&1; then
    exit
  fi

  if [[ $(pass find "infra/mc" | wc -l) -gt 1 ]]; then
    mkdir -p "${HOME}/.mc"
    pass show "infra/ssh" >>"${HOME}/.mc/config.json"
    chmod 600 "${HOME}/.mc/config.json"
  fi
}
