#!/usr/bin/env bash

export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

if [[ -d ${HOME}/homebrew ]]; then
  export PATH="${HOME}/homebrew/sbin:${HOME}/homebrew/bin:${PATH}"
fi

if command -v brew > /dev/null 2>&1; then
  CURL_PATH="$(brew --prefix)/opt/curl/bin"
  export PATH="${CURL_PATH}:${PATH}"
fi
