#!/usr/bin/env bash

export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha

if [[ -d "${HOME}/homebrew" ]]; then
  export PATH="${HOME}/homebrew/sbin:${HOME}/homebrew/bin:${PATH}"
fi
