#!/usr/bin/env bash

if [[ -d "${HOME}/opt/python" ]]; then
  export PYTHONUSERBASE="${HOME}/opt/python"
  export PATH="${HOME}/opt/python/bin:${PATH}"
fi

if [[ -d "${HOME}/opt/pyenv" ]]; then
  export PYENV_ROOT="${HOME}/opt/pyenv"
  export PATH="${PYENV_ROOT}/bin:${PATH}"

  if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
  fi
fi
