#!/usr/bin/env bash

if [[ -d "${HOME}/opt/pyenv" ]]; then
  export PYENV_ROOT="${HOME}/opt/pyenv"
  export PATH="${PYENV_ROOT}/bin:${PATH}"

  if command -v pyenv 1>/dev/null 2>&1; then
    export PYTHONUSERBASE="${HOME}/opt/python"

    eval "$(pyenv init -)"
  fi
fi
