#!/usr/bin/env bash

if command -v brew > /dev/null 2>&1; then
  PYTHON_PATH="${BREW_PREFIX}/opt/python/libexec/bin"
  export PATH="${PYTHON_PATH}:${PATH}"
  unset PYTHON_PATH
fi

if [[ -d "${HOME}/opt/python" ]]; then
  export PYTHONUSERBASE="${HOME}/opt/python"
  export PATH="${PYTHONUSERBASE}/bin:${PATH}"
fi
