#!/usr/bin/env bash

backup() {
  tar -czf - . | pv | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${1:-$(passget "infra/backup" aes)}" >"$(basename "$(pwd)").tar.gz.gpg"
}

upload() {
  mc mv "${1:-$(basename "$(pwd)")}.tar.gz.gpg" "scw/fibr/"
}

restore() {
  local BASE_FILENAME="${1:-backup}"

  mkdir "${BASE_FILENAME}"
  gpg --decrypt --batch --passphrase "${2:-$(passget "infra/backup" aes)}" "${BASE_FILENAME}.tar.gz.gpg" | pv | tar -xz -C "${BASE_FILENAME}" -
}
