#!/usr/bin/env bash

backup() {
  tar -czf - . | pv | gpg --symmetric --cipher-algo AES256 --batch --passphrase "${1:-$("$(pass show "infra/backup" | awk -F': ' '$1 == "aes" {printf("%s", $2)}')")}" >"$(basename "$(pwd)").tar.gz.gpg"
}

upload() {
  mc mv "${1:-$(basename "$(pwd)")}.tar.gz.gpg" "scw/fibr/"
}

restore() {
  local BASE_FILENAME="${1:-backup}"

  mkdir "${BASE_FILENAME}"
  gpg --decrypt --batch --passphrase "${2:-$("$(pass show "infra/backup" | awk -F': ' '$1 == "aes" {printf("%s", $2)}')")}" "${BASE_FILENAME}.tar.gz.gpg" | pv | tar -xz -C "${BASE_FILENAME}" -
}
