#!/usr/bin/env bash

if command -v brew >/dev/null 2>&1; then
  if [[ -f "${BREW_PREFIX:-}/etc/bash_completion" ]]; then
    source "${BREW_PREFIX:-}/etc/bash_completion"
  fi
elif [[ -f /etc/bash_completion ]]; then
  source "/etc/bash_completion"
fi

# Enter a folder name to `cd` to it
shopt -s autocd

# Fix minor spelling issues with `cd`
shopt -s cdspell

# Fix minor spelling issues for commands
shopt -s dirspell

# history configuration
export HISTCONTROL=ignoreboth:erasedups
export LESSHISTFILE=/dev/null

# When the shell exits, append to the history file instead of overwriting it
shopt -s histappend
