#!/usr/bin/env bash

function cert_create_ca() {
    if [ "${#}" -eq 0 ]; then
        echo Usage cert_create_ca [CN_NAME] [CERT_PASSWORD]
    fi

    local CN_NAME="${1}"
    readVariableIfRequired "CN_NAME"

    local CERT_PASSWORD="${2}"
    readVariableIfRequired "CERT_PASSWORD"

    local DIRECTORY="./CA"
    mkdir -p "${DIRECTORY}"

    CA=${DIRECTORY}/ca.pem
    CA_PK=${DIRECTORY}/ca-private-key

    echo Creating Certificate Authority
    openssl genrsa -aes256 -out ${CA_PK} -passout pass:${CERT_PASSWORD} 4096
    openssl req -subj "/CN=${CN_NAME}" -new -x509 -days 365 -key ${CA_PK} -sha256 -out ${CA} -passin pass:${CERT_PASSWORD}

    chmod -v 0400 "${CA_PK}"
    chmod -v 0444 "${CA}"
}

function cert_create_cert() {
    if [ "${#}" -eq 0 ]; then
        echo Usage cert_create_cert [NAME] [HOST_IP] [CA_PRIVATE_KEY_PASSWORD]
    fi

    local NAME="${1}"
    readVariableIfRequired "NAME"

    local HOST_IP="${2}"
    readVariableIfRequired "HOST_IP"

    local CA_PRIVATE_KEY_PASSWORD="${3}"
    readVariableIfRequired "CA_PRIVATE_KEY_PASSWORD"

    local DIRECTORY="./${NAME}-cert"
    local CA_DIRECTORY="./CA"
    mkdir -p "${DIRECTORY}"
    cp "${CA_DIRECTORY}/ca.pem" "${DIRECTORY}/ca.pem"

    local CSR="${DIRECTORY}/${NAME}.csr"
    local EXT="${DIRECTORY}/extfile.cnf"
    local CERT="${DIRECTORY}/cert.pem"
    local KEY="${DIRECTORY}/key.pem"
    local CA="${DIRECTORY}/ca.pem"
    local CA_PK="${CA_DIRECTORY}/ca-private-key"

    echo Creating private key and Certificate
    openssl genrsa -out "${KEY}" 4096
    openssl req -subj "/CN=${NAME}" -sha256 -new -key "${KEY}" -out "${CSR}"
    echo subjectAltName = IP:${HOST_IP},IP:127.0.0.1 > "${EXT}"
    openssl x509 -req -days 365 -sha256 -in "${CSR}" -CA "${CA}" -CAkey "${CA_PK}" -CAcreateserial -out "${CERT}" -extfile "${EXT}" -passin "pass:${CA_PRIVATE_KEY_PASSWORD}"

    rm -f "${CSR}" "${EXT}" .srl
    chmod -v 0400 "${KEY}"
    chmod -v 0444 "${CERT}"
}