#!/usr/bin/env sh

function os_clean() {
  if [ `uname` == 'Darwin' ]; then
    sudo find / -name ".DS_Store" -exec rm -f {} \;
    sudo find / -name ".localized" -exec rm -f {} \;
  fi
  if [ `uname` == 'Linux' ]; then
    sudo sync; echo 3 > /proc/sys/vm/drop_caches
  fi
}
