#!/usr/bin/env bash

if [ command -v brew > /dev/null 2>&1 ]; then
    source `brew --prefix`/etc/bash_completion
else
    if [ -e /var/bash-completion/bash_completion ]; then
        source /var/bash-completion/bash_completion
    fi
fi
