#!/usr/bin/env bash

alias dev='cd ${HOME}/code/'
alias grep='grep --color=auto'
alias vi='vim'
alias fuck='sudo $(history -p \!\!)'

export EDITOR='vim'
export TERM='xterm-256color'

if command -v xdg-open >/dev/null 2>&1 && ! command -v open >/dev/null 2>&1; then
  alias open='xdg-open'
fi

random() {
  openssl rand -hex "${1:-30}"
}

meteo() {
  curl --disable --silent --show-error --location --max-time 30 -4 "wttr.in/${1:-Paris}?m&format=v2"
}

rainbow() {
  awk '
  BEGIN{
    s="          "; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
      r = 255-(colnum*255/76);
      g = (colnum*510/76);
      b = (colnum*255/76);
      if (g>255) g = 510-g;
      printf "\033[48;2;%d;%d;%dm", r,g,b;
      printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
      printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
  }'
}

loadtest() {
  if [[ ${#} -lt 1 ]]; then
    var_error "Usage: loadtest URL RATE_PER_SECOND"
    return 1
  fi

  local URL=${1}
  shift
  local RATE=${1}
  shift || true

  printf "GET %s" "${URL}" | vegeta attack -rate="${RATE:-50}" -duration=30s | vegeta plot >vegeta.html && open vegeta.html
}

if command -v systemctl >/dev/null 2>&1; then
  status() {
    sudo systemctl status "${@}"
  }

  restart() {
    sudo systemctl restart "${@}"
  }

  logs() {
    sudo journalctl -u "${@}"
  }
fi
