#!/usr/bin/env bash

if command -v colima >/dev/null 2>&1; then
  docker_start() {
    colima start --runtime=containerd
  }

  docker_stop() {
    colima stop
    colima delete --force
  }
fi

if command -v docker >/dev/null 2>&1; then
  export DOCKER_CONTENT_TRUST="1"

  docker_clean() {
    docker ps --all --quiet | xargs docker rm --volumes
    docker images --quiet | xargs docker rmi
    docker images --format '{{ .Repository }}:{{ .Tag}}' | xargs docker rmi
    docker network ls --format '{{ json .}}' | jq --raw-output 'select(.Name != "bridge" and .ID != "") | .Name' | xargs docker network rm
    docker volume ls --quiet | xargs docker volume rm
  }

  sidecars_stop() {
    docker stop "rabbit"
    docker stop "postgres"
    docker stop "redis"

    docker rm --volumes "rabbit"
    docker rm --volumes "postgres"
    docker rm --volumes "redis"
  }

  sidecars_start() {
    sidecars_stop

    docker run --detach --name "rabbit" --publish "127.0.0.1:5672:5672" --publish "127.0.0.1:15672:15672" "rabbitmq:management"
    docker run --detach --name "postgres" --env "POSTGRES_PASSWORD=postgres" --publish "127.0.0.1:5432:5432" "postgres"
    docker run --detach --name "redis" --publish "127.0.0.1:6379:6379" "redis"
  }

  datadog_agent() {
    docker run --name datadog --rm --env "DD_API_KEY=${DATADOG_APIKEY}" --env "DD_ENV=localhost" --env "DD_HOSTNAME=$(whoami)" --publish "8126:8126/tcp" datadog/agent
  }
fi
