#!/usr/bin/env bash

if [ -e "${HOME}/.fzf.bash" ]; then
  source "${HOME}/.fzf.bash"

  if command -v fd > /dev/null 2>&1; then
    export FZF_DEFAULT_COMMAND='fd --hidden --follow --exclude .git --exclude node_modules --exclude vendor --exclude vendors'
    export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
  fi
fi
