#!/usr/bin/env bash

if [ -f ~/.fzf.bash ]; then
  source ~/.fzf.bash

  # Setting ag as the default source for fzf
  export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'

  # To apply the command to CTRL-T as well
  export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
fi
