#!/usr/bin/env bash

if ! command -v fzf > /dev/null 2>&1; then
  return
fi

if command -v git > /dev/null 2>&1; then
  function git_lg_preview() {
    fzf --ansi --reverse --tiebreak=index --no-sort --preview 'f() { set -- $(echo -- "$@" | grep -o "[a-f0-9]\{7\}"); [ $# -eq 0 ] || git show --color=always $1; }; f {}'
  }
fi

if command -v pass > /dev/null 2>&1; then
  function _fzf_complete_pass() {
    FZF_COMPLETION_TRIGGER='' _fzf_complete '-1' "${@}" < <(
      local PASS_DIR=${PASSWORD_STORE_DIR-~/.password-store}
      find "${PASS_DIR}" -name '*.gpg' -print | sed -e "s|${PASS_DIR}/\(.*\)\.gpg$|\1|"
    )
  }
  [ -n "${BASH}" ] && complete -F _fzf_complete_pass -o default -o bashdefault pass

  function passfor() {
    pass -c "${1}"

    if [ $? -eq 0 ] && [ `pass show "${1}" | grep '^otpauth:' | wc -l` -eq 1 ]; then
      read -s -p "  Press enter for otp"
      echo ""

      pass otp -c "${1}"
    fi
  }
  [ -n "${BASH}" ] && complete -F _fzf_complete_pass -o default -o bashdefault passfor
fi

if command -v make > /dev/null 2>&1; then
  function _fzf_complete_make() {
    FZF_COMPLETION_TRIGGER='' _fzf_complete '-1' "${@}" < <(make -rpn | sed -n -e '/^$/ { n ; /^[^ .#][^ ]*:/ { s/:.*$// ; p ; } ; }')
  }
  [ -n "${BASH}" ] && complete -F _fzf_complete_make -o default -o bashdefault make
fi

if command -v ssh > /dev/null 2>&1; then
  function _fzf_complete_ssh_notrigger() {
    FZF_COMPLETION_TRIGGER='' _fzf_complete_ssh
  }
  [ -n "${BASH}" ] && complete -F _fzf_complete_ssh_notrigger -o default -o bashdefault ssh
fi

if command -v pgcli > /dev/null 2>&1; then
  function _fzf_complete_pgcli() {
    FZF_COMPLETION_TRIGGER='' _fzf_complete '-1' "${@}" < <(
      cat "${PGPASSFILE-${HOME}/.pgpass}" | egrep -v '^\s*#' | egrep -v '^$' | awk '{split($0,parts,":"); print "host: " parts[1] " user: " parts[4] " db: " parts[3]}'
    )
  }

  function _fzf_complete_pgcli_post() {
    awk '{print "-h " $2 " -U " $4 " " $6}'
  }

  [ -n "${BASH}" ] && complete -F _fzf_complete_pgcli -o default -o bashdefault pgcli
fi
