#!/usr/bin/env bash

if ! command -v fzf > /dev/null 2>&1; then
  return
fi

if command -v node > /dev/null 2>&1 && command -v jq > /dev/null 2>&1; then
  _fzf_complete_npm() {
    if [ ! -e "package.json" ]; then
      return
    fi

    if [ "${3}" == 'run' ]; then
      local entries=`jq --raw-output '.scripts | paths | add' package.json`

      _fzf_complete '--reverse' "$@" < <(
        echo "${entries}"
      )
    fi
  }

  [ -n "$BASH" ] && complete -F _fzf_complete_npm -o default -o bashdefault npm
fi

if command -v git > /dev/null 2>&1; then
  _fzf_complete_git() {
    if ! `git rev-parse --is-inside-work-tree 2>/dev/null`; then
      return
    fi

    if [ "${3}" == 'checkout' ]; then
      local entries=`git branch -vv`

      _fzf_complete '--reverse' "$@" < <(
        echo "${entries}"
      )
    fi
  }

  _fzf_complete_git_post() {
      awk '{print $1}'
  }

  [ -n "$BASH" ] && complete -F _fzf_complete_git -o default -o bashdefault git
fi

if command -v pass > /dev/null 2>&1; then
  _fzf_complete_pass() {
    local PASS_DIR=${PASSWORD_STORE_DIR-~/.password-store}
    local entries=`find "$PASS_DIR" -name "*.gpg" -print | sed -e "s|${PASS_DIR}/\(.*\)\.gpg$|\1|"`

    _fzf_complete '--reverse' "$@" < <(
      echo "${entries}"
    )
  }

  [ -n "$BASH" ] && complete -F _fzf_complete_pass -o default -o bashdefault pass
fi
