#!/usr/bin/env bash

if ! command -v git >/dev/null 2>&1; then
  return
fi

if command -v delta >/dev/null 2>&1; then
  export GIT_PAGER='delta --dark'
fi

...() {
  cd "$(git_root)" || return 1
}

jira_pull_request() {
  local GIT_CURRENT_BRANCH
  GIT_CURRENT_BRANCH="$(git current-branch)"

  local JIRA_TICKET_ID
  JIRA_TICKET_ID="$(jira print "${GIT_CURRENT_BRANCH}")"

  github_pull_request "$(git remote-repository)" "$(jira summary "${JIRA_TICKET_ID}")" "$(git default-branch)" "${GIT_CURRENT_BRANCH}"
  jira transition "${JIRA_TICKET_ID}" "in review"
}
