#!/bin/sh

cat > ${HOME}/.gitconfig <<GITCONFIG
[user]
	name = Vincent Boutour
	email = bob@vibioh.fr
[core]
	editor = vi
	autocrlf = input
	excludesfile = ${HOME}/.gitignore_global
[color]
	ui = true
[push]
	default = simple
[alias]
	lg = log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
	tidy = rebase -i @{u}
[credential]
	helper = cache --timeout=28800
[fetch]
	prune = true
[pull]
	rebase = preserve
GITCONFIG

