#!/usr/bin/env bash

GPG_TTY="$(tty)"
export GPG_TTY

gpg_agent_stop() {
  gpgconf --kill gpg-agent
}

cipher() {
  gpg --symmetric --cipher-algo AES256 "${@}" | base64
}

decipher() {
  base64 -D | gpg --decrypt "${@}"
}

cipher_for() {
  if [[ ${#} -lt 2 ]]; then
    printf "%bUsage: cipher_for GITHUB_USERNAME FILE_TO_ENCRYPT%b\n" "${RED}" "${RESET}"
    return 1
  fi

  local TEMP_GNUPGHOME
  TEMP_GNUPGHOME="$(mktemp -d)"

  cp "${GNUPGHOME:-${HOME}/.gnupg/gpg.conf}" "${TEMP_GNUPGHOME}/gpg.conf"

  local PUBLIC_KEY
  PUBLIC_KEY="$(mktemp)"

  curl --disable --silent --show-error --location --max-time 10 "https://github.com/${1}.gpg" >"${PUBLIC_KEY}"
  gpg --homedir "${TEMP_GNUPGHOME}" --import "${PUBLIC_KEY}"

  local RECIPIENT
  RECIPIENT="$(gpg --homedir "${TEMP_GNUPGHOME}" --list-keys --with-colons | grep uid | awk -F: '{print $10}' | uniq | fzf --height=20 --ansi --reverse --prompt "Email:")"

  gpg --homedir "${TEMP_GNUPGHOME}" --encrypt --recipient "${RECIPIENT}" "${2}"

  rm -rf "${TEMP_GNUPGHOME}" "${PUBLIC_KEY}"
}
