#!/usr/bin/env bash

if command -v python > /dev/null 2>&1; then
  alias realpath="python -c 'import sys; import os.path; print(os.path.realpath(sys.argv[1]))'"
fi

meteo() {
  curl -q -sSL --max-time 30 -4 "wttr.in/${1:-Paris}?m&format=v2"
}
