#!/usr/bin/env bash

if [[ "${OSTYPE}" =~ ^darwin ]]; then
  export CLICOLOR=1
  export LS_OPTIONS=""
  export LSCOLORS="ExFxCxDxBxEgEdAbAgAcAd"
else
  export LS_OPTIONS="--color=auto"
fi

alias ll='ls ${LS_OPTIONS} -hAltr'
