#!/usr/bin/env bash

open_ports() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    sudo lsof -PniTCP -sTCP:LISTEN
  elif command -v ss >/dev/null 2>&1; then
    sudo ss -plant
  elif command -v netstat >/dev/null 2>&1; then
    sudo netstat -pluton
  fi
}

dns_flush_cache() {
  if command -v unbound-control >/dev/null 2>&1; then
    local UNBOUND_CONF_FOLDER="${BREW_PREFIX:-}/etc/unbound"
    local UNBOUND_DNSSEC_CERT="${UNBOUND_CONF_FOLDER}/root.key"
    local UNBOUND_CONF_FILE="${UNBOUND_CONF_FOLDER}/unbound.conf"

    sudo unbound-anchor -a "${UNBOUND_DNSSEC_CERT}"
    sudo unbound-control -c "${UNBOUND_CONF_FILE}" -q reload 2>/dev/null || true
    sudo unbound-control -c "${UNBOUND_CONF_FILE}" -q stop 2>/dev/null || true

    printf "Waiting 1 second before starting again...\n"
    sleep 1

    sudo unbound-control -c "${UNBOUND_CONF_FILE}" -q start
  fi

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    sudo dscacheutil -flushcache
    sudo killall -HUP mDNSResponder
  else
    if [[ $(systemctl list-units systemd-resolve* | wc -l) -gt 2 ]]; then
      sudo systemd-resolve --flush-caches
    fi
  fi
}

dns_block() {
  cat \
    <(curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/${BLOCKED_HOSTS:-fakenews-gambling-porn-social}/hosts") \
    <(curl --disable --silent --show-error --location --max-time 30 "https://someonewhocares.org/hosts/zero/hosts") |
    grep --extended-regexp --invert-match '^$' |
    grep --extended-regexp --invert-match '^\s*#' |
    grep --extended-regexp '^(0.0.0.0|127.0.0.1|255.255.255.255|::1|fe00::|ff02::)' |
    tr -s '[:blank:]' ' ' |
    tr '[:upper:]' '[:lower:]' |
    sort --unique |
    grep --extended-regexp '^0.0.0.0 ' |
    awk '{print "local-zone: \""$2"\" refuse"}' |
    sort --unique >"${HOME}/.unbound-blocklist"
}

dns_allow() {
  declare -A websites

  websites["reddit"]="
      preview.redd.it
      v.redd.it
      redd.it
      alb.reddit.com
      external-preview.redd.it
      gateway.reddit.com
      gql.reddit.com
      oauth.reddit.com
      www.reddit.com
      reddit.com
      styles.redditmedia.com
      thumbs.redditmedia.com
      www.redditmedia.com
      redditmedia.com
      www.redditstatic.com
      reddit.map.fastly.net
  "

  websites["linkedin"]="
    www.linkedin.com
    linkedin.com
    media.licdn.com
    static.licdn.com
  "

  websites["aws"]="analytics.console.aws.a2z.com"

  websites["mtv"]="
    googlesyndication.com
    pagead2.googlesyndication.com
  "

  local WEBSITE
  WEBSITE="$(printf "%s\n" "${!websites[@]}" | fzf --height=20 --ansi --reverse --select-1 --query="${1:-}" --exit-0)"

  if [[ -z ${WEBSITE} ]]; then
    return 1
  fi

  local GREP_PIPELINE=()

  for entry in ${websites[${WEBSITE}]}; do
    GREP_PIPELINE+=("-e" "\"${entry}\"")
  done

  local UNBOUND_BLOCKLIST
  UNBOUND_BLOCKLIST=$(mktemp -t unbound)

  grep --invert-match "${GREP_PIPELINE[@]}" "${HOME}/.unbound-blocklist" >"${UNBOUND_BLOCKLIST}"

  mv "${UNBOUND_BLOCKLIST}" "${HOME}/.unbound-blocklist"

  dns_flush_cache
}
