#!/usr/bin/env bash

open_ports() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    sudo lsof -PniTCP -sTCP:LISTEN
  elif command -v ss >/dev/null 2<&1; then
    sudo ss -plant
  elif command -v netstat >/dev/null 2<&1; then
    sudo netstat -pluton
  fi
}

dns_flush_cache() {
  if command -v unbound-control >/dev/null 2>&1; then
    sudo unbound-control -q reload
  fi

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    sudo dscacheutil -flushcache
    sudo killall -HUP mDNSResponder
  else
    if [[ $(systemctl list-units systemd-resolve* | wc -l) -gt 2 ]]; then
      sudo systemd-resolve --flush-caches
    fi
  fi
}
