#!/usr/bin/env bash

if command -v nnn > /dev/null 2>&1; then
  export NNN_USE_EDITOR=1
  export NNN_TMPFILE="/tmp/nnn"

  function nn() {
    nnn "$@"

    if [ -f "${NNN_TMPFILE}" ]; then
      . "${NNN_TMPFILE}"
      rm -f "${NNN_TMPFILE}" > /dev/null
    fi
  }
fi
