#!/usr/bin/env bash

if ! command -v n > /dev/null 2>&1; then
  return
fi

export N_PREFIX="${HOME}/opt"

if ! command -v node > /dev/null 2>&1; then
  return
fi

export PATH="${HOME}/opt/node/bin:${PATH}"
alias npmi="npm install --ignore-scripts"
