#!/usr/bin/env bash

notes_erase() {
  if [[ -d ${NOTES_FOLDER:-${HOME}/notes} ]]; then
    rm -rf "${NOTES_FOLDER:-${HOME}/notes}"
  fi
}

notes() {
  local NOTE_ACTION="${1:-}"
  shift || true

  local REAL_NOTE_FOLDER="${NOTES_FOLDER:-${HOME}/notes}"

  case "${NOTE_ACTION}" in
  "open" | "")
    "${NOTE_EDITOR:-${EDITOR}}" "${REAL_NOTE_FOLDER}"
    ;;

  "save")
    (
      cd "${REAL_NOTE_FOLDER}" || return
      git add -A
      git commit --signoff -m "docs: $(date +"%Y-%m-%dT%H:%M:%S%z")"
    )
    ;;

  "sync")
    (
      if ! [[ -d ${REAL_NOTE_FOLDER} ]]; then
        git clone "git@github.com:ViBiOh/notes.git" "${REAL_NOTE_FOLDER}"
        cd "${REAL_NOTE_FOLDER}" || return
        sublime_add_project
      else
        cd "${REAL_NOTE_FOLDER}" || return
        git pp
      fi
    )
    ;;

  esac
}
