#!/bin/sh

RED="\[\033[31m\]"
GREEN="\[\033[32m\]"
YELLOW="\[\033[33m\]"
BLUE="\[\033[34m\]"
PURPLE="\[\033[35m\]"
RESET="\[\033[0m\]"

if [ `which git 2>/dev/null | wc -l` -eq 0 ] || [ ! `type -t git_info` ]; then
  export PS1="${BLUE}\u${RESET}@${RED}\h${RESET} ${GREEN}\w${RESET} ツ"
else
  export PS1="${BLUE}\u${RESET}@${RED}\h${RESET} ${GREEN}\w${RESET}${YELLOW}\$(git_info)${RESET} ツ"
fi
