#!/usr/bin/env bash

export PYENV_ROOT="${HOME}/opt/pyenv"
export PATH="${PYENV_ROOT}/bin:${PATH}"

if command -v pyenv 1>/dev/null 2>&1; then
  export PYTHONUSERBASE="$(pyenv root)"

  eval "$(pyenv init -)"
fi
