#!/usr/bin/env bash

if command -v gem > /dev/null 2>&1; then
  GEM_USER_PATH="$(gem env | grep 'USER INSTALLATION DIRECTORY' | sed 's|.*USER INSTALLATION DIRECTORY: \(.*\)|\1|')"
  if [[ -n ${GEM_USER_PATH:-} ]]; then
    export PATH="${GEM_USER_PATH}/bin:${PATH}"
  fi

  unset GEM_USER_PATH
fi
