#!/usr/bin/env sh

function sed_escape_string() {
  echo ${1} | sed 's|\([\|\.]\)|\\\1|g'
}

function sed_replace_properties() {
  sed -i '' -e "s|^`sed_escape_string ${2}`.*|`sed_escape_string ${4:-${2}}`=`sed_escape_string ${3}`|" ${1}
}
