#!/usr/bin/env bash

SSH_ENV="${HOME}/.ssh/environment"
SSH_KEY="${HOME}/.ssh/id_ed25519"

if [[ ! -e "${SSH_KEY}" ]]; then
  SSH_KEY="${HOME}/.ssh/id_rsa"
fi

start_ssh_agent() {
  if [[ -e "${SSH_KEY}" ]]; then
    echo "Initializing new SSH agent..."

    touch "${SSH_ENV}"
    chmod 600 "${SSH_ENV}"

    ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
    source "${SSH_ENV}" > /dev/null
    ssh-add -k "${SSH_KEY}"
  fi
}

stop_ssh_agent() {
  if [[ -n "${SSH_AGENT_PID:-}" ]]; then
    kill -0 "${SSH_AGENT_PID}" 2>/dev/null
  fi
}

if [[ -f "${SSH_ENV}" ]]; then
  source "${SSH_ENV}" > /dev/null

  if [[ -n "${SSH_AGENT_PID:-}" ]]; then
    kill -0 "${SSH_AGENT_PID}" 2>/dev/null || {
      start_ssh_agent
    }
  fi
else
    start_ssh_agent
fi
