#!/usr/bin/env bash

function readVariableIfRequired() {
  if [ -z "${!1}" ]; then
    read -p "${2:-${1}=}" "${1}"
  else
    echo "${1}="${!1}
  fi
}

function trim() {
    local var="$*"

    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"

    echo -n "$var"
}
