#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
      cd "$(dirname "${FILE_SOURCE}")" && pwd
    )
  fi
}

install() {
  local PACKAGES=("bash" "bash-completion" "make" "grep" "htop" "openssl" "curl" "ncdu" "jq" "pv")

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    cat >"${HOME}/.bash_profile" <<END_OF_BASH_PROFILE
#!/usr/bin/env bash

if [[ -f "${HOME}/.bashrc" ]]; then
  source "${HOME}/.bashrc"
fi
END_OF_BASH_PROFILE

    if ! command -v brew >/dev/null 2>&1; then
      /bin/bash -c "$(curl --disable --silent --show-error --location "https://raw.githubusercontent.com/Homebrew/install/master/install.sh")"
      source "$(script_dir)/../sources/_homebrew"
    fi

    packages_update
    packages_install "${PACKAGES[@]}" "awk" "iftop"

    if [[ $(grep --count "${BREW_PREFIX}" "/etc/shells") -eq 0 ]]; then
      printf "+-------------------------+\n"
      printf "| changing shell for user |\n"
      printf "+-------------------------+\n"

      printf "%s/bin/bash\n" "${BREW_PREFIX}" | sudo tee -a "/etc/shells" >/dev/null
      chsh -s "${BREW_PREFIX}/bin/bash" -u "$(whoami)"
    fi
  elif command -v apt-get >/dev/null 2>&1; then
    packages_update
    packages_install "apt-transport-https"
    packages_install "${PACKAGES[@]}" dnsutils jdupes
  elif command -v pacman >/dev/null 2>&1; then
    packages_update
    packages_install "${PACKAGES[@]}" inetutils tcpdump
  fi
}
