#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  packages_install_desktop alacritty

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    ln -f -s "/Applications/Alacritty.app/Contents/MacOS/alacritty" "${HOME}/opt/bin/alacritty"
  fi
}
