#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  if package_exists alacritty; then
    packages_install_desktop alacritty
  fi

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    ln -f -s "/Applications/Alacritty.app/Contents/MacOS/alacritty" "${HOME}/opt/bin/alacritty"
  fi
}
