#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.mc"
}

install() {
  curl_to_binary "https://dl.min.io/client/mc/release/$(normalized_os)-$(normalized_arch "amd64" "arm" "arm64")/mc" "mc"
}

credentials() {
  if ! command -v pass >/dev/null 2>&1; then
    return
  fi

  if [[ ! -d ${PASSWORD_STORE_DIR:-${HOME}/.password-store} ]]; then
    return
  fi

  extract_secret "infra/mc" ".mc/config.json"
}
