#!/usr/bin/env bash

if [[ $(pgrep -a bash | wc -l) -eq 1 ]]; then
  if [[ $(type -t ssh_agent_stop) == "function" ]]; then
    ssh_agent_stop
  fi

  if [[ $(type -t stop_gpg_agent) == "function" ]]; then
    stop_gpg_agent
  fi
fi

clear
