#!/usr/bin/env bash

[[ -z "${PS1}" ]] && return

for file in "${HOME}/code/src/github.com/ViBiOh/dotfiles/sources/"*; do
  [[ -r "${file}" ]] && [[ -f "${file}" ]] && source "${file}"
done

if [[ -e "${HOME}/.localrc" ]]; then
  source "${HOME}/.localrc"
fi
