#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

stock() {
  local YAHOO_OUTPUT
  YAHOO_OUTPUT="$(
    curl \
      --disable \
      --silent \
      --show-error \
      --location \
      --max-time 10 \
      --header "User-Agent: Mozilla/5.0" \
      --fail-with-body \
      "https://query1.finance.yahoo.com/v8/finance/chart/${1:-DDOG}?&includePrePost=true&interval=1h&range=1d"
  )"

  if [[ ${?} -ne 0 ]]; then
    return 1
  fi

  local EVOLUTION_PERCENT
  local EVOLUTION_SIGN="↗"
  local EVOLUTION_COLOR="#[fg=brightgreen]"

  _stock_evolution() {
    EVOLUTION_PERCENT="$(printf -- "scale = 4; 100 * ((%s / %s) - 1)" "${CURRENT_PRICE}" "${PREVIOUS_PRICE}" | bc)"

    EVOLUTION_SIGN="↗"

    if [[ ${EVOLUTION_PERCENT} =~ ^- ]]; then
      EVOLUTION_SIGN="↘"
      EVOLUTION_COLOR="#[fg=brightred]"
      EVOLUTION_PERCENT="${EVOLUTION_PERCENT#-}"
    elif [[ ${EVOLUTION_PERCENT} == 0 ]]; then
      EVOLUTION_SIGN="→"
      EVOLUTION_COLOR="#[fg=brightyellow]"
    fi
  }

  local CURRENT_PRICE
  CURRENT_PRICE="$(printf -- "%s" "${YAHOO_OUTPUT}" | jq --raw-output '.chart.result[0].meta | .regularMarketPrice')"

  local PREVIOUS_PRICE
  PREVIOUS_PRICE="$(printf -- "%s" "${YAHOO_OUTPUT}" | jq --raw-output '.chart.result[0].meta | .previousClose')"

  _stock_evolution
  printf -- "%s %s%s%s" "${CURRENT_PRICE}" "${EVOLUTION_COLOR}" "${EVOLUTION_SIGN}" "${EVOLUTION_PERCENT%00}%"
}

stock DDOG
