" Turnoff vi backward compatibility
set nocompatible

" Plugins configuration
call plug#begin('~/.vim/vim-plug')

Plug 'vim-airline/vim-airline'
Plug 'airblade/vim-gitgutter'

call plug#end()

" Line highlight
set cursorline

" Show line numbers
set number

" Default file encoding
set encoding=utf-8

" Show current command combination on bottom right
set showcmd

" Confirm change save
set confirm

" Wrap lines
set wrap

" Spaces tab's width and indent size
set tabstop=2 shiftwidth=2
if exists(':filetype')
  filetype indent on
endif

" Show matching parenthesis
set showmatch

" Insert spaces instead of tabs
set expandtab

" Backspace behavior for corresponding to most common apps
set backspace=indent,eol,start

" Hightlight search
set hlsearch

" Clear highlight when pressing escape
nnoremap <esc> :noh<return><esc>
nnoremap <esc>^[ <esc>^[

" Search as you type character
set incsearch

" Ignore case in search
set ignorecase

" Search with smart case (if uppercase provided, search is case sensitive)
set smartcase

" Omni completion
set completeopt=longest,menuone
set omnifunc=syntaxcomplete#Complete

" Auto reload file
set autoread

" Disable folding
set nofoldenable

" Disable backup files
set nobackup
set noswapfile

" Enable syntax color if exist
if exists(":syntax")
  syntax on
endif

" Change map leader if possible
if exists(":let")
  let mapleader=","
endif

" Disabling viminfo
set viminfo=""

" Turn on the Wild menu, better suggestion
set wildmenu

" Be lazy when redrawing screen
set lazyredraw

" Search using ctrl-p and fzf
set rtp+=~/opt/fzf
noremap <C-p> :FZF<return>

" Redirecting output to shell to null
set shellpipe=>

" Using ripgrep for searching
if executable("rg")
  set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
  nnoremap <Leader>g :silent lgrep -P<Space>
endif

" Opening quickfix automatically
if exists(':autocmd')
  autocmd QuickFixCmdPost [^l]* nested cwindow
  autocmd QuickFixCmdPost    l* nested lwindow
endif

" Save file with sudo permission
if exists(':execute')
  command W :execute ':silent w !sudo tee % > /dev/null' | :edit!
endif
