#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  sudo rm -rf "${HOME}/.cache"
  sudo rm -rf "${HOME}/.config/htop"
  sudo rm -rf "${HOME}/opt"

  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  rm -rf "${SCRIPT_DIR}/../scripts"
}

install() {
  mkdir -p "${HOME}/opt/bin"
}
