#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  cat \
    <(curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/${BLOCKED_HOSTS:-fakenews-gambling-porn-social}/hosts") \
    <(curl --disable --silent --show-error --location --max-time 30 "https://someonewhocares.org/hosts/zero/hosts") \
    <(printf "127.0.0.1 %s\n::1 %s\n" "$(hostname)" "$(hostname)") |
    grep --extended-regexp --invert-match '^$' |
    grep --extended-regexp --invert-match '^\s*#' |
    grep --extended-regexp '^(0.0.0.0|127.0.0.1|255.255.255.255|::1|fe00::|ff02::)' |
    tr -s '[:blank:]' ' ' |
    tr '[:upper:]' '[:lower:]' |
    sort --unique |
    grep --invert-match "ɢ" |
    grep --invert-match "0.0.0.0 alb.reddit.com" |
    grep --invert-match "0.0.0.0 external-preview.redd.it" |
    grep --invert-match "0.0.0.0 gateway.reddit.com" |
    grep --invert-match "0.0.0.0 gql.reddit.com" |
    grep --invert-match "0.0.0.0 linkedin.com" |
    grep --invert-match "0.0.0.0 media.licdn.com" |
    grep --invert-match "0.0.0.0 oauth.reddit.com" |
    grep --invert-match "0.0.0.0 preview.redd.it" |
    grep --invert-match "0.0.0.0 reddit.com" |
    grep --invert-match "0.0.0.0 reddit.map.fastly.net" |
    grep --invert-match "0.0.0.0 redditmedia.com" |
    grep --invert-match "0.0.0.0 static.licdn.com" |
    grep --invert-match "0.0.0.0 styles.redditmedia.com" |
    grep --invert-match "0.0.0.0 v.redd.it" |
    grep --invert-match "0.0.0.0 www.linkedin.com" |
    grep --invert-match "0.0.0.0 www.reddit.com" |
    grep --invert-match "0.0.0.0 www.redditmedia.com" |
    grep --invert-match "0.0.0.0 www.redditstatic.com" |
    grep --invert-match "thumbs.redditmedia.com" |
    sed $'s|0.0.0.0 \(.*\)|0.0.0.0 \\1\\\n0:0:0:0:0:0:0:0 \\1|g' |
    sudo tee "/etc/hosts" >/dev/null
}
