#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  rm -rf "${SCRIPT_DIR}/../scripts"
}

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  (
    cd "${SCRIPT_DIR}/../"
    curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/main/bootstrap" | bash -s "var" "git" "git_hooks" "github" "version" "ssh" "kube_pg_restore" "rotate" "http"
  )
}
