#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  rm -rf "${SCRIPT_DIR}/../scripts"
}

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  (
    cd "${SCRIPT_DIR}/../"
    curl -q -sSL --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "var" "git" "git_hooks" "github" "version" "release" "ssh" "tmux" "docker_registry_cleanup" "slack_cleaner" "release"
  )
}
