#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  if command -v brew >/dev/null 2>&1; then
    brew cask install alacritty
    ln -f -s "/Applications/Alacritty.app/Contents/MacOS/alacritty" "${HOME}/opt/bin/alacritty"
  fi
}
