#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  packages_install unbound

  local UNBOUND_CONF_FOLDER="${BREW_PREFIX:-}/etc/unbound"
  local UNBOUND_CONF_FILE="${UNBOUND_CONF_FOLDER}/unbound.conf"
  local UNBOUND_CA_CERT="${UNBOUND_CONF_FOLDER}/ca-certificates.pem"
  local UNBOUND_DNSSEC_CERT="${UNBOUND_CONF_FOLDER}/root.key"

  sudo curl --disable --silent --show-error --location --max-time 30 "https://curl.se/ca/cacert.pem" --output "${UNBOUND_CA_CERT}"
  sudo chmod 600 "${UNBOUND_CA_CERT}"
  sudo chown "root" "${UNBOUND_CA_CERT}"

  echo "server:
  verbosity: 1
  username: root
  chroot: ''

  interface: 127.0.0.1
  port: 53

  access-control: 0.0.0.0/0 refuse
  access-control: 127.0.0.0/8 allow

  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes

  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  use-caps-for-id: yes

  cache-min-ttl: 3600
  cache-max-ttl: 86400

  tls-cert-bundle: \"${UNBOUND_CA_CERT}\"
  auto-trust-anchor-file: \"${UNBOUND_DNSSEC_CERT}\"

  use-syslog: no
  logfile: /var/log/unbound.log

  include: \"${HOME}/.unbound-blocklist\"

remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
  server-key-file: \"${UNBOUND_CONF_FOLDER}/unbound_server.key\"
  server-cert-file: \"${UNBOUND_CONF_FOLDER}/unbound_server.pem\"
  control-key-file: \"${UNBOUND_CONF_FOLDER}/unbound_control.key\"
  control-cert-file: \"${UNBOUND_CONF_FOLDER}/unbound_control.pem\"

${UNBOUND_EXTRA_DNS_CONF:-}

forward-zone:
  name: .
  forward-addr: 2606:4700:4700::1111@853#cloudflare-dns.com
  forward-addr: 1.0.0.1@853#cloudflare-dns.com
  forward-addr: 2606:4700:4700::1001@853#cloudflare-dns.com
  forward-addr: 1.0.0.1@853#cloudflare-dns.com
  forward-ssl-upstream: yes
" | sudo tee "${UNBOUND_CONF_FILE}" >/dev/null

  sudo unbound-anchor -a "${UNBOUND_DNSSEC_CERT}"
  if ! [[ -e "${UNBOUND_DNSSEC_CERT}/unbound_server.key" ]]; then
    sudo unbound-control-setup -d "${UNBOUND_CONF_FOLDER}"
  fi

  sudo unbound-control -c "${UNBOUND_CONF_FILE}" -q reload || true
  sudo unbound-control -c "${UNBOUND_CONF_FILE}" -q stop || true
  sudo unbound-control -c "${UNBOUND_CONF_FILE}" -q start

  echo "nameserver 127.0.0.1" | sudo tee "/etc/resolv.conf" >/dev/null

  if command -v brew >/dev/null 2>&1; then
    sudo networksetup -setdnsservers "Wi-Fi" 127.0.0.1
    sudo networksetup -setsearchdomains "Wi-Fi" local
  fi

  if command -v resolvconf >/dev/null 2>&1; then
    if [[ -d /etc/NetworkManager/ ]]; then
      printf "dns=none\n" | sudo tee "/etc/NetworkManager/NetworkManager.conf" >/dev/null
    fi

    echo "resolv_conf=/etc/resolv.conf
name_servers=127.0.0.1" | sudo tee "/etc/resolvconf.conf" >/dev/null
    sudo resolvconf -u
  fi
}
