#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local UNBOUND_CONF="/etc/unbound/unbound.conf"
  local UNBOUND_DNSSEC_CERT="/usr/local/etc/unbound/root.key"
  local UNBOUND_CONTROL_FOLDER="/usr/local/etc/unbound"

  packages_install unbound
  if command -v brew >/dev/null 2>&1; then
    UNBOUND_CONF="$(brew --prefix)${UNBOUND_CONF}"
  fi

  echo "server:
  verbosity: 1
  username: root
  chroot: ''

  interface: 127.0.0.1
  interface: ::1
  port: 53

  access-control: 0.0.0.0/0 refuse
  access-control: 127.0.0.0/8 allow
  access-control: ::0/0 refuse
  access-control: ::1 allow

  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes

  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  use-caps-for-id: yes

  cache-min-ttl: 3600
  cache-max-ttl: 86400

  auto-trust-anchor-file: \"${UNBOUND_DNSSEC_CERT}\"

  use-syslog: no
  logfile: /var/log/unbound.log

  include: \"${HOME}/.unbound-blocklist\"

remote-control:
  control-enable: yes
  control-interface: 127.0.0.1
  server-key-file: \"${UNBOUND_CONTROL_FOLDER}/unbound_server.key\"
  server-cert-file: \"${UNBOUND_CONTROL_FOLDER}/unbound_server.pem\"
  control-key-file: \"${UNBOUND_CONTROL_FOLDER}/unbound_control.key\"
  control-cert-file: \"${UNBOUND_CONTROL_FOLDER}/unbound_control.pem\"

forward-zone:
  name: .
  forward-addr: 1.1.1.1@853
  forward-addr: 1.0.0.1@853
  forward-ssl-upstream: yes

${UNBOUND_EXTRA_DNS_CONF:-}" | sudo tee "${UNBOUND_CONF}" >/dev/null

  sudo unbound-anchor -a "${UNBOUND_DNSSEC_CERT}"
  if ! [[ -e "${UNBOUND_DNSSEC_CERT}/unbound_server.key" ]]; then
    sudo unbound-control-setup -d "${UNBOUND_CONTROL_FOLDER}"
  fi

  sudo unbound-control -c "${UNBOUND_CONF}" -q reload || true
  sudo unbound-control -c "${UNBOUND_CONF}" -q stop || true
  sudo unbound-control -c "${UNBOUND_CONF}" -q start

  echo "nameserver 127.0.0.1" | sudo tee "/etc/resolv.conf" >/dev/null

  if command -v brew >/dev/null 2>&1; then
    sudo networksetup -setdnsservers "Wi-Fi" 127.0.0.1
    sudo networksetup -setsearchdomains "Wi-Fi" local
  fi

  if command -v resolvconf >/dev/null 2>&1; then
    if [[ -d /etc/NetworkManager/ ]]; then
      printf "dns=none\n" | sudo tee "/etc/NetworkManager/NetworkManager.conf" >/dev/null
    fi

    echo "resolv_conf=/etc/resolv.conf
name_servers=127.0.0.1" | sudo tee "/etc/resolvconf.conf" >/dev/null
    sudo resolvconf -u
  fi
}
