#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  if command -v colima >/dev/null 2>&1; then
    colima delete --force
  fi

  sudo rm -rf "${HOME}/.docker"
  sudo rm -rf "${HOME}/.lima"
  sudo rm -rf "${HOME}/.colima"
}

install() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    packages_install "colima" "docker"
    brew unlink docker && brew link docker

    colima completion bash >"${SCRIPT_DIR}/../sources/colima-completion"

    local DOCKER_COMPOSE_VERSION="2.2.3"
    curl_to_binary "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-$(normalized_os)-$(normalized_arch)" "docker-compose"
  fi
}
