#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  if command -v colima >/dev/null 2>&1; then
    colima delete --force
  fi

  sudo rm -rf "${HOME}/.docker"
  sudo rm -rf "${HOME}/.lima"
  sudo rm -rf "${HOME}/.colima"
}

install() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    packages_install "colima"
    colima completion bash >"${SCRIPT_DIR}/../sources/colima-completion"
    colima nerdctl install --path "${HOME}/opt/bin/docker"
  fi
}
