#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    brew install git
  elif command -v apt-get > /dev/null 2>&1; then
    sudo apt-get install -y -qq --no-install-recommends git
  fi

  if ! command -v git > /dev/null 2>&1; then
    return
  fi

  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  curl -q -sSL --max-time 30 -o "${SCRIPT_DIR}/../sources/git-prompt" "https://raw.githubusercontent.com/git/git/v$(git --version | awk '{print $3}')/contrib/completion/git-prompt.sh"

  local DELTA_VERSION="0.3.0"
  local DELTA_OS="-unknown-linux-musl"

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    DELTA_OS="-apple-darwin"
  fi

  archive_to_binary "https://github.com/dandavison/delta/releases/download/${DELTA_VERSION}/delta-${DELTA_VERSION}-x86_64${DELTA_OS}.tar.gz" "delta-${DELTA_VERSION}-x86_64${DELTA_OS}/delta"
}
