#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  packages_install git

  if ! command -v git >/dev/null 2>&1; then
    return
  fi

  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  curl --disable --silent --show-error --location --max-time 30 --output "${SCRIPT_DIR}/../sources/git-prompt" "https://raw.githubusercontent.com/git/git/v$(git --version | awk '{print $3}')/contrib/completion/git-prompt.sh"

  local DELTA_VERSION="0.6.0"

  local OS="unknown-linux-musl"
  local ARCH
  ARCH="$(normalized_arch "" "arm")"

  if [[ $(normalized_os) =~ ^darwin ]]; then
    OS="apple-darwin"
  elif [[ ${ARCH} == "aarch64" ]]; then
    OS="unknown-linux-gnu"
  elif [[ ${ARCH} == "arm" ]]; then
    OS="unknown-linux-gnueabihf"
  fi

  local DELTA_RELEASE="delta-${DELTA_VERSION}-${ARCH}-${OS}"
  archive_to_binary "https://github.com/dandavison/delta/releases/download/${DELTA_VERSION}/${DELTA_RELEASE}.tar.gz" "${DELTA_RELEASE}/delta"
}
