#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local HIDAPITESTER_VERSION="0.2"

  archive_to_binary "https://github.com/todbot/hidapitester/releases/download/${HIDAPITESTER_VERSION}/hidapitester-$(normalized_os "macos")-$(normalized_arch "" "armv7l" "arm64").zip" hidapitester
}
