#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.mc"
}

install() {
  curl_to_binary "https://dl.min.io/client/mc/release/$(normalized_os)-$(normalized_arch "amd64" "arm" "arm64")/mc" "mc"
}

credentials() {
  extract_secret "infra/mc" ".mc/config.json"
}
