#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local BUF_VERSION="v1.0.0-rc1"

  local OS
  OS="$(normalized_os)"
  local ARCH
  ARCH="$(normalized_arch)"

  curl_to_binary "https://github.com/bufbuild/buf/releases/download/${BUF_VERSION}/buf-${OS}-${ARCH}" "buf"
  curl_to_binary "https://github.com/bufbuild/buf/releases/download/${BUF_VERSION}/protoc-gen-buf-lint-${OS}-${ARCH}" "protoc-gen-buf-lint"
}
