#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.python_history"
}

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

  packages_install python

  if command -v brew >/dev/null 2>&1; then
    brew unlink "python" && brew link "python"
  fi

  if ! command -v python >/dev/null 2>&1; then
    return
  fi

  mkdir -p "${HOME}/opt/python"
  source "${SCRIPT_DIR}/../sources/_first"
  source "${SCRIPT_DIR}/../sources/_python"

  if ! command -v pip >/dev/null 2>&1; then
    return
  fi

  pip install --user --upgrade pip
}
