#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  sudo rm -rf "${HOME}/.pgpass"
  sudo rm -rf "${HOME}/.config/pgcli"
}

credentials() {
  if ! command -v pass >/dev/null 2>&1; then
    exit
  fi

  local PASS_DIR="${PASSWORD_STORE_DIR:-${HOME}/.password-store}"
  local PG_PASS
  PG_PASS="$(find "${PASS_DIR}" -name "*pgpass.gpg" -print | sed -e "s|${PASS_DIR}/\(.*\)\.gpg$|\1|")"

  if [[ $(echo "${PG_PASS}" | wc -l) -eq 1 ]]; then
    pass show "${PG_PASS}" >"${HOME}/.pgpass"
    chmod 600 "${HOME}/.pgpass"
  fi
}

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "${SCRIPT_DIR}/../sources/_python"

  if ! command -v pip >/dev/null 2>&1; then
    var_error "pip is required"
    exit
  fi

  if command -v brew >/dev/null 2>&1; then
    brew install pgcli
  elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get install -y -qq --no-install-recommends libpq-dev
    pip install --user pgcli
  fi

  if ! command -v pgcli >/dev/null 2>&1; then
    return
  fi

  mkdir -p "${HOME}/.config/pgcli"

  echo "[main]
multi_line = True
auto_expand = True
row_limit = 100" >"${HOME}/.config/pgcli/config"
}
