#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.ansible"*[^.cfg]
}

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "${SCRIPT_DIR}/../sources/_python"

  if ! command -v pip >/dev/null 2>&1; then
    var_error "pip is required"
    exit
  fi

  pip install --user ansible ansible-lint jmespath yamllint
}

credentials() {
  if ! command -v pass >/dev/null 2>&1; then
    exit
  fi

  if [[ $(pass find ansible | wc -l) -gt 1 ]]; then
    pass show "dev/ansible" >"${HOME}/.ansible-vault-pass"
    chmod 600 "${HOME}/.ansible-vault-pass"
  fi
}
