#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  sudo rm -rf "${HOME}/.pgpass"
  sudo rm -rf "${HOME}/.config/pgcli"
}

install() {
  local SCRIPT_DIR
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  source "${SCRIPT_DIR}/../sources/_python"

  if ! command -v pip >/dev/null 2>&1; then
    var_error "pip is required"
    exit
  fi

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    packages_install pgcli
  elif command -v apt-get >/dev/null 2>&1; then
    packages_install libpq-dev
    pip install --user pgcli
  fi

  if ! command -v pgcli >/dev/null 2>&1; then
    return
  fi

  mkdir -p "${HOME}/.config/pgcli"

  echo "[main]
multi_line = True
auto_expand = True
row_limit = 100" >"${HOME}/.config/pgcli/config"
}

credentials() {
  if ! command -v pass >/dev/null 2>&1; then
    exit
  fi

  if [[ $(pass find pgpass | wc -l) -gt 1 ]]; then
    pass show "infra/pgpass" >>"${HOME}/.pgpass"
    chmod 600 "${HOME}/.pgpass"
  fi
}
