#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
      cd "$(dirname "${FILE_SOURCE}")" && pwd
    )
  fi
}

clean() {
  rm -rf "${HOME}/.ansible"*[^.cfg]
}

install() {
  source "$(script_dir)/../sources/_python"

  if ! command -v pip >/dev/null 2>&1; then
    var_error "pip is required"
    exit
  fi

  pip install --user ansible==3.4.0 ansible-lint jmespath yamllint
}

credentials() {
  if ! command -v pass >/dev/null 2>&1; then
    exit
  fi

  if [[ $(pass find ansible | wc -l) -gt 1 ]]; then
    pass show "dev/ansible" >"${HOME}/.ansible-vault-pass"
    chmod 600 "${HOME}/.ansible-vault-pass"
  fi
}
