#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  cat \
    <(curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts") \
    <(curl --disable --silent --show-error --location --max-time 30 "https://someonewhocares.org/hosts/zero/hosts") \
    <(printf "127.0.0.1 %s\n" "$(hostname)") |
    grep --extended-regexp --invert-match '^$' |
    grep --extended-regexp --invert-match '^\s*#' |
    grep --extended-regexp '^(0.0.0.0|127.0.0.1|255.255.255.255|::1|fe00::|ff02::)' |
    tr -s '[:blank:]' ' ' |
    sort --unique |
    grep --invert-match "ɢ" |
    grep --invert-match "0.0.0.0 www.linkedin.com" |
    grep --invert-match "0.0.0.0 static.licdn.com" |
    grep --invert-match "0.0.0.0 media.licdn.com" |
    grep --invert-match "0.0.0.0 reddit.com" |
    grep --invert-match "0.0.0.0 www.reddit.com" |
    grep --invert-match "0.0.0.0 gateway.reddit.com" |
    grep --invert-match "0.0.0.0 oauth.reddit.com" |
    grep --invert-match "0.0.0.0 www.redditstatic.com" |
    grep --invert-match "0.0.0.0 alb.reddit.com" |
    grep --invert-match "0.0.0.0 redditmedia.com" |
    grep --invert-match "0.0.0.0 www.redditmedia.com" |
    grep --invert-match "thumbs.redditmedia.com" |
    grep --invert-match "0.0.0.0 preview.redd.it" |
    grep --invert-match "0.0.0.0 external-preview.redd.it" |
    grep --invert-match "0.0.0.0 v.redd.it" |
    grep --invert-match "0.0.0.0 styles.redditmedia.com" |
    grep --invert-match "0.0.0.0 reddit.map.fastly.net" |
    sed $'s|0.0.0.0 \(.*\)|0.0.0.0 \\1\\\n0:0:0:0:0:0:0:0 \\1|g' |
    sudo tee /etc/hosts >/dev/null

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    defaults write NSGlobalDomain AppleEnableMenuBarTransparency -bool false
    defaults write NSGlobalDomain AppleFontSmoothing -int 1
    defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
    defaults write NSGlobalDomain AppleLanguages -array "en"
    defaults write NSGlobalDomain AppleLocale -string "en_US@currency=EUR"
    defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
    defaults write NSGlobalDomain AppleMetricUnits -bool true
    defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
    defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true
    defaults write NSGlobalDomain InitialKeyRepeat -int 15
    defaults write NSGlobalDomain KeyRepeat -int 2
    defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
    defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
    defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
    defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
    defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
    defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true
    defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
    defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

    defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

    defaults write com.apple.finder AppleShowAllFiles -bool true
    defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
    defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
    defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
    defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
    defaults write com.apple.finder ShowPathbar -bool true
    defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
    defaults write com.apple.finder ShowStatusBar -bool true
    defaults write com.apple.finder DisableAllAnimations -bool true

    defaults write com.apple.Safari AutoFillCreditCardData -bool false
    defaults write com.apple.Safari AutoFillFromAddressBook -bool false
    defaults write com.apple.Safari AutoFillMiscellaneousForms -bool false
    defaults write com.apple.Safari AutoFillPasswords -bool false
    defaults write com.apple.Safari AutoOpenSafeDownloads -bool false
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabled -bool false
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaEnabledForLocalFiles -bool false
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2JavaScriptCanOpenWindowsAutomatically -bool false
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2PluginsEnabled -bool false
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true
    defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2
    defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false
    defaults write com.apple.Safari HomePage -string "about:blank"
    defaults write com.apple.Safari IncludeDevelopMenu -bool true
    defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true
    defaults write com.apple.Safari ShowFavoritesBar -bool false
    defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true
    defaults write com.apple.Safari ShowSidebarInTopSites -bool false
    defaults write com.apple.Safari SuppressSearchSuggestions -bool true
    defaults write com.apple.Safari UniversalSearchEnabled -bool false
    defaults write com.apple.Safari WarnAboutFraudulentWebsites -bool true
    defaults write com.apple.Safari WebAutomaticSpellingCorrectionEnabled -bool false
    defaults write com.apple.Safari WebContinuousSpellCheckingEnabled -bool false
    defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
    defaults write com.apple.Safari WebKitJavaEnabled -bool false
    defaults write com.apple.Safari WebKitJavaScriptCanOpenWindowsAutomatically -bool false
    defaults write com.apple.Safari WebKitPluginsEnabled -bool false
    defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true

    defaults write com.apple.screensaver askForPassword -int 1
    defaults write com.apple.screensaver askForPasswordDelay -int 0

    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

    defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

    defaults write com.apple.dock tilesize -int 36
    defaults write com.apple.dock autohide -bool true
    defaults write com.apple.dock autohide-delay -float 0
    defaults write com.apple.dock autohide-time-modifier -float 0
    defaults write com.apple.dock showhidden -bool true
    defaults write com.apple.dock hide-mirror -bool true
    defaults write com.apple.dock mineffect -string "scale"
    defaults write com.apple.dock minimize-to-application -bool true
    defaults write com.apple.dock launchanim -bool false

    defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

    defaults write com.apple.ActivityMonitor ShowCategory -int 0
    defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
    defaults write com.apple.ActivityMonitor SortDirection -int 0

    defaults write com.apple.DiskUtility DUDebugMenuEnabled -bool true
    defaults write com.apple.DiskUtility advanced-image-options -bool true

    defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true
    defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
    defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1
    defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

    defaults write com.apple.CrashReporter DialogType none

    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true

    defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40

    defaults write com.apple.screencapture disable-shadow -bool true
    defaults write com.apple.screencapture location -string "${HOME}/Downloads"
    defaults write com.apple.screencapture type -string "png"

    sudo systemsetup -setrestartfreeze on
    sudo systemsetup -setwakeonnetworkaccess off

    sudo pmset -a hibernatemode 0
    sudo pmset -a lidwake 1
    sudo pmset -a sms 0
    sudo pmset -b displaysleep 5
    sudo pmset -b sleep 10
    sudo pmset -c displaysleep 10
    sudo pmset -c sleep 15

    fix_spotlight

    sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName
    sudo defaults write /Library/Preferences/com.apple.loginwindow GuestEnabled -bool false
    sudo defaults write /Library/Preferences/com.apple.loginwindow RetriesUntilHint -int 0
    sudo defaults write /Library/Preferences/com.apple.loginwindow showInputMenu -bool true
    sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool true
    sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.captive.control Active -bool false

    sudo nvram SystemAudioVolume=" "
    sudo scutil --set ComputerName macbook
    sudo scutil --set HostName macbook
    sudo scutil --set LocalHostName macbook

    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode on
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode on
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsigned off
    sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsignedapp off
    sudo pkill -HUP socketfilterfw

    chflags nohidden "${HOME}/Library"

    csrutil status
  fi
}
