#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local SHELLCHECK_VERSION="v0.7.1"

  local ARCH
  ARCH="$(normalized_arch)"

  local OS
  OS="$(normalized_os)"

  archive_to_binary "https://github.com/koalaman/shellcheck/releases/download/${SHELLCHECK_VERSION}/shellcheck-${SHELLCHECK_VERSION}.${OS}.${ARCH}.tar.xz" "shellcheck"
}
