#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.siege"
}

install() {
  packages_install siege

  mkdir -p "${HOME}/.siege"

  echo "verbose = true
color = on
json_output = false
gmethod = GET
parser = false
cache = false
concurrent = 10
delay = 5
internet = false
benchmark = false" >"${HOME}/.siege/siege.conf"
}
