#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  if command -v brew >/dev/null 2>&1; then
    brew reinstall sublime-text sublime-merge

    ln -f -s "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" "${HOME}/opt/bin/subl"
  fi

  if command -v subl >/dev/null 2>&1; then
    local SCRIPT_DIR
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

    "${SCRIPT_DIR}/../sublime/init"
  fi
}
