#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local SYNCTHING_VERSION="1.12.1"

  local OS
  OS="$(normalized_os)"

  if [[ ${OS} == "darwin" ]]; then
    OS="macos"
  fi

  local SYNCTHING_RELEASE
  SYNCTHING_RELEASE="syncthing-${OS}-$(normalized_arch "amd64" "arm")-v${SYNCTHING_VERSION}"
  archive_to_binary "https://github.com/syncthing/syncthing/releases/download/v${SYNCTHING_VERSION}/${SYNCTHING_RELEASE}.zip" "${SYNCTHING_RELEASE}/syncthing"
}
