#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  local SYNCTHING_VERSION="1.16.1"

  local OS
  OS="$(normalized_os)"

  if [[ ${OS} == "darwin" ]]; then
    OS="macos"
  fi

  local SYNCTHING_RELEASE
  SYNCTHING_RELEASE="syncthing-${OS}-$(normalized_arch "amd64" "arm" "arm64")-v${SYNCTHING_VERSION}"

  local SYNCTHIN_ARCHIVE_TYPE="tar.gz"
  if [[ ${OSTYPE} =~ ^darwin ]]; then
    SYNCTHIN_ARCHIVE_TYPE="zip"
  fi

  archive_to_binary "https://github.com/syncthing/syncthing/releases/download/v${SYNCTHING_VERSION}/${SYNCTHING_RELEASE}.${SYNCTHIN_ARCHIVE_TYPE}" "${SYNCTHING_RELEASE}/syncthing"
}
