#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.terraform"*
}

install() {
  local TERRAFORM_VERSION="0.13.5"

  local OS
  OS="$(uname -s | tr "[:upper:]" "[:lower:]")"
  local ARCH
  ARCH="$(uname -m | tr "[:upper:]" "[:lower:]")"

  if [[ ${ARCH} == "x86_64" ]]; then
    ARCH="amd64"
  elif [[ ${ARCH} =~ ^armv.l$ ]]; then
    ARCH="arm"
  fi

  archive_to_binary "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${OS}_${ARCH}.zip" "terraform"

  mkdir -p "${HOME}/.terraform.d/plugin-cache"
  printf "plugin_cache_dir = \"%s/.terraform.d/plugin-cache\"\n" "${HOME}" >"${HOME}/.terraformrc"
}

credentials() {
  if ! command -v pass >/dev/null 2>&1; then
    exit
  fi

  if [[ $(pass find terraform | wc -l) -gt 1 ]]; then
    printf "credentials \"app.terraform.io\" {\ntoken = \"%s\"\n}" "$(pass show "dev/terraform" | grep "^token: " | sed 's|^[^ ]*: ||')" >>"${HOME}/.terraformrc"
    chmod 600 "${HOME}/.terraformrc"
  fi
}
