#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.vim/"
  rm -rf "${HOME}/.viminfo"
}

install() {
  if command -v brew >/dev/null 2>&1; then
    brew install vim
    brew install --HEAD universal-ctags/universal-ctags/universal-ctags
  elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get install --yes -qq --no-install-recommends vim
  fi

  curl --disable --silent --show-error --location --max-time 30 -o "${HOME}/.vim/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  vim +PlugInstall +qall < /dev/tty
}
