#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME}/.vim/"
  rm -rf "${HOME}/.viminfo"
}

install() {
  packages_install vim

  curl --disable --silent --show-error --location --max-time 30 -o "${HOME}/.vim/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  vim +PlugInstall +qall </dev/tty
}
