#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

clean() {
  rm -rf "${HOME:?}/.vim/"
  rm -rf "${HOME:?}/.viminfo"
}

install() {
  if command -v brew >/dev/null 2>&1; then
    brew install vim
  elif command -v apt-get >/dev/null 2>&1; then
    sudo apt-get install -y -qq --no-install-recommends vim
  fi

  curl -q -sSL --max-time 30 -o "${HOME}/.vim/autoload/plug.vim" --create-dirs "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  vim +:PlugInstall +qall
}
