---
name: Renovate

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pages: none
  pull-requests: write
  repository-projects: none
  security-events: write

on:
  schedule:
    - cron: "0/15 * * * *"

defaults:
  run:
    shell: bash

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Renovate
        uses: renovatebot/github-action@v36.1.1
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
